services:
  namenode:
    #    image: bde2020/hadoop-namenode
    build:
      context: .
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_STREAMING_JAR=/opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./:/app

  datanode:
    image: bde2020/hadoop-datanode
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    links:
      - namenode:namenode